[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_ui = "0.12.1"
bevy_text = "0.12.1"
bevy_simple_text_input = "0.3.1"